In [1]:
import numpy as np
from src.sim_data import sim_data
from src.logit_lasso import logit_lasso


np.set_printoptions(formatter={'float': '{: 0.6f}'.format})
family = "logit"
rho = 0.5
n, p, s = 400, 1000, 6
pmax = 10
beta_0 = [0.05, 3, -2.5, 3.5, -1.5, -3]
beta_1 = np.zeros(p - s)
beta = np.append(beta_0, beta_1)
x, y = sim_data(beta, rho, n, family)

b, is_active, lamb, df = logit_lasso(x, y, pmax=10)
print(b[:10])
print(b[is_active])
print(lamb)

df=  1
[ 0.075321 -0.251603]
df=  1
[ 0.075326 -0.251791]
df=  2
[ 0.075496  0.040313 -0.288909]
df=  2
[ 0.078236  0.280258 -0.516511]
df=  3
[ 0.076892  0.306744  0.033263 -0.556923]
df=  3
[ 0.067784  0.469455  0.232572 -0.809023]
df=  3
[ 0.067732  0.470298  0.233584 -0.810345]
df=  4
[ 0.065633  0.493752  0.270934 -0.028728 -0.835907]
df=  5
[ 0.061759  0.535414 -0.000051  0.336110 -0.078551 -0.881836]
df=  5
[ 0.060821  0.564977 -0.035339  0.376256 -0.097012 -0.900796]
df=  6
[ 0.059618  0.608723 -0.086360  0.435804 -0.124153 -0.930382  0.010254]
df=  6
[ 0.056614  0.711783 -0.203230  0.574115 -0.186459 -1.003238  0.033604]
df=  8
[ 0.054535  0.754401 -0.249141  0.630198 -0.210102 -1.036429  0.007450
 -0.010772  0.042623]
df=  9
[ 0.053033  0.784512 -0.281164  0.669610 -0.226570 -1.060321  0.012663
 -0.018696  0.048895 -0.000001]
df=  9
[ 0.052424  0.802156 -0.299933  0.693233 -0.236743 -1.074727  0.015940
 -0.023418  0.052918 -0.003839]
df=  11
[ 0.052056  0.842048 -0.342781  0.

In [2]:
from scipy.stats import norm
from scipy import linalg as sl
import numpy as np
from src.sigma_mat import sigma_ma
from src.resp_family import resp_family
from scipy.stats import norm, bernoulli, poisson
from scipy import linalg

In [4]:
np.shape(b)

(1000,)

In [3]:
def test(x, y):
    x = x + 1
    y = y + 1
    return x

x = 1
y = 1
x = test(x, y)
print(x)
print(y)

2
1


In [4]:
def test(x, y):
    x.append('b')
    y.append('b')
    return x

x = ['a']
y = ['a']
x = test(x, y)
print(x)
print(y)

['a', 'b']
['a', 'b']
